# Generated by Django 6.0.3 on 2026-03-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('testing', 'Testing'), ('tools', 'Tools')], max_length=20)),
                ('proficiency_level', models.IntegerField(help_text='Proficiency level from 1 to 100')),
                ('icon', models.CharField(help_text='Icon class name or SVG path', max_length=50)),
            ],
        ),
    ]
