# Generated by Django 6.0.3 on 2026-03-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('frontend Framework', 'Frontend Framework'), ('backend', 'Backend'), ('backend Framework', 'Backend Framework'), ('testing', 'Testing'), ('tools', 'Tools')], max_length=20),
        ),
    ]
