# Generated by Django 6.0.3 on 2026-03-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='case_study',
            field=models.TextField(blank=True, null=True),
        ),
    ]
